### ISSUE TITLE
Example ?

### ISSUE THREAD

**Issue by JFOC** [appstract/laravel-multisite#10]
Hi,
do you have the example of using this package ?

**Comment by gizburdt** [comment]
I will write a Medium post about the package :)

**Comment by JFOC** [comment]
Cant wait ;)

**Comment by teuunn** [comment]
Me neither!

**Comment by JFOC** [comment]
Hi, Do you have the article now ?

**Comment by gizburdt** [comment]
Sorry, very busy atm :(
