### ISSUE TITLE
Is this working with Laravel 5.4?

### ISSUE THREAD

**Issue by prnxdev** [appstract/laravel-multisite#2]
Hi. Is this package working with L 5.4? Cause when I type 

```
php artisan vendor:publish --provider="Appstract\Multisite\MultisiteServiceProvider"
```

nothing is publishing :/

**Comment by gizburdt** [comment]
Thanks for the issue, will have a look at it :)

**Comment by prnxdev** [comment]
I found missing one thing in README.md

You have to add 
```
Appstract\Multisite\MultisiteServiceProvider::class
```

to config/app.php

and It's working fine then :).

**Comment by gizburdt** [comment]
Nice, I will add it to the readme

**Comment by prnxdev** [comment]
One more question - with this package can I create one codebase and pin few domains (not subdomains) and what about sessions? They are shared or private (for every domain individuall)? I mean if i will login on one page (which is pinned ofc. to mine codebase) I will be logged on other page (which is pinned ofc. to same codebase)?

**Comment by gizburdt** [comment]
The domain part (not subdomains) is the one part that is not completely tested yet.

Sessions and stuff are shared, since they both use the same folder, config etc.

**Comment by prnxdev** [comment]
Ok, thanks a lot :)

**Comment by gizburdt** [comment]
NP :)
