### ISSUE TITLE
Laravel 5.3 missing aliasMiddleware

### ISSUE THREAD

**Issue by luukverhoeven** [appstract/laravel-multisite#4]
aliasMiddleware doesn't exists.

![image](https://cloud.githubusercontent.com/assets/995760/23848096/d9767768-07d5-11e7-8615-770f1a1a40df.png)

It can be fixed by adding this to **MultisiteServiceProvider**: 
```
   // Middleware
        if (method_exists($router, 'aliasMiddleware')) {
            $router->aliasMiddleware('site', CurrentSite::class);
        } else {
            $router->middleware('site', CurrentSite::class);
        }
```

**Comment by gizburdt** [comment]
Thanks, pushed a fix
