### ISSUE TITLE
domain setup

### ISSUE THREAD

**Issue by frogjimjaff** [appstract/laravel-multisite#7]
Hi

I'm having trouble with the last few steps in the setup guide.

Can you give we a real world example of what data I put in the sites database table?

currently i have.

name = test1
slug = test1.homestead.app
route is blank?
url = test1

I don't understand what I need to put put into routes/web.php ?
I dont have the $currentSite var availble

Could you give me some examples and guidence please?

ta

**Comment by teuunn** [comment]
Hi @frogjimjaff,

A database example:

| id | name     | slug       | route                         | url                  |
|---|---------|---------|---------------------|--------------|
| 1  | Cool       | cool       | NULL                         | http://cool.dev|
| 2  | Support | support | support.homepage  | NULL |

The routes need to get grouped per site, like:

```
Route::group([
    'domain' => config('multisite.host'),
    'as' => 'cool.',
    'middleware' => 'site:cool'
], function () {
    // Your 'cool-site' routes, for example:
    Route::name('homepage')->get('/', 'CoolController@homepage');
});

Route::group([
    'domain' => 'support.'.config('multisite.host'),
    'as' => 'support.',
    'middleware' => 'site:support'
], function () {
    // Your 'support-site' routes, for example:
    Route::name('homepage')->get('/', 'SupportController@homepage');
});
```

Give it a shot and let us know.  👍🏻

**Comment by frogjimjaff** [comment]
Thanks for the quick and helpful reply! 

I now have the controller being called correctly but I cannot access the $currentSite var within it

 public function homepage() {
        
        var_dump($currentSite);
        die("here");
    }
     
gives me Undefined variable: currentSite.

any ideas?

My setup is:

INSERT INTO `sites` (`id`, `name`, `slug`, `route`, `url`)
VALUES
	(1, 'dealer1', 'dealer1', '', 'http://dealer1.homestead.app'),
	(2, 'dealer2', 'dealer2', NULL, 'http://dealer2.homestead.app');



Routes

Route::group([
'domain' => 'dealer1.'.config('multisite.host'),
'as' => 'dealer1.',
'middleware' => 'site:dealer1'
], function () {

Route::name('homepage')->get('/', 'productController@homepage');
});


Route::group([
'domain' => 'dealer2.'.config('multisite.host'),
'as' => 'dealer2.',
'middleware' => 'site:dealer2'
], function () {

Route::name('homepage')->get('/', 'productController@homepage');
});

**Comment by teuunn** [comment]
It is possible by doing Site::where('slug', Config::get('multisite.site'))->first(), but we decided to make a nice helper to get it: **current_site()**, check the [commit](https://github.com/appstract/laravel-multisite/blob/master/src/helpers.php)

Closing it for now. If you can't get it to work, please reopen 👍

**Comment by teuunn** [comment]
@frogjimjaff 

I see you edited your reply.

I think in your case you only need to set the "core-site" url homestead.app. 
The url of the subdomeins don't need to be set separately.

**Comment by frogjimjaff** [comment]
I updated  and your current_site() method is working..

Thanks for the great support.
