### ISSUE TITLE
current_site returns null in controller contructor

### ISSUE THREAD

**Issue by frogjimjaff** [appstract/laravel-multisite#8]
Hi 

I have an issue ithat within my controller __construct method the current_site function returns null i.e the multi_site object hasn't yet been setup.

 public function __construct()
{

//this returns null
    var_dump(current_Site());

}

public function index()
{
    //this works
    var_dump(current_Site());

}

Is there a way to have the current site helper function available in the contructor?

Thanks

**Comment by teuunn** [comment]
Hi @frogjimjaff 

Laravel handles the middlewares after the construct. Reusing the controller by multiple routes will give problems if you set the site in the construct. For example: You can use two different subdomains who both use the same controller. But those sites are different, so setting the construct doesn't keep it dynamic. 

Before L5.3 it was different, check [this article](https://laravel-news.com/controller-construct-session-changes-in-laravel-5-3)

Hope this explains why. Maybe there's a way to figure it out?
Keep us posted! Thanks :)

**Comment by frogjimjaff** [comment]
OK thanks for your help
