### ISSUE TITLE
Homestead

### ISSUE THREAD

**Issue by shraddhabanerjee** [appstract/laravel-multisite#9]
Hi,

Do I need to install the vagrant box & homestead for using this plugin.  If yes what is the sequence of installation & the folder structure?

1. Laravel
2. Vagrant Box
3. Homestead
 What is the folder structure.

Sorry if it is a very basic question but as I am very new to all this I am unable to make out what is going wrong.

**Comment by gizburdt** [comment]
Do you already have a Homestead installation running?

**Comment by shraddhabanerjee** [comment]
@gizburdt No I dont have homestead. But I want ti use this plugin for multisite in laravel. Is it possible? Thanks for your reply.

**Comment by gizburdt** [comment]
How do you run your local Laravel projects?

**Comment by shraddhabanerjee** [comment]
I have laravel 5.4 installation done from here : https://www.howtoforge.com/tutorial/install-laravel-on-ubuntu-for-apache/

**Comment by gizburdt** [comment]
Then you can install the package with composer and follow the instructions. Only the `/etc/hosts` and `Homestead.yaml` steps are different. I don't know how this should be fixed on Ubuntu.

**Comment by shraddhabanerjee** [comment]
Not sure what to do with Homestead.yaml as I don't have it & not necessary as I have all other included softwares of Homestead installed on my machine in ubuntu...

**Comment by gizburdt** [comment]
Then you should point your domains to your application, and proceed with the next steps from our instructions.
